{
 "title": "FTD Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "Data Source", "query": "influxdb" },
   {
    "name": "deviceName",
    "query": {
     "query": "SHOW TAG VALUES WITH key = \"deviceName\" WHERE deviceName != 'Hacks-Home-FTD [PRODUCTION!!!]' and deviceName != 'Paradise [!! PRODUCTION !!!]'"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"interface\" WHERE deviceName = '${deviceName}'"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Bytes Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface::tag" ], "type": "tag" },
      { "params": [ "deviceName::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_interfaceHealthMetrics",
     "query": "SELECT mean(\"outputBytesAvg\"), mean(\"inputBytesAvg\") FROM \"ftd_interfaceHealthMetrics\" WHERE (\"deviceName\"::tag =~ /^$deviceName$/ AND \"interface\"::tag =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval), \"interface\"::tag fill(null)",
     "select": [
      [
       { "params": [ "outputBytesAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" },
      { "condition": "AND", "key": "interface::tag", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Bytes In",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface::tag" ], "type": "tag" },
      { "params": [ "deviceName::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_interfaceHealthMetrics",
     "query": "SELECT mean(\"outputBytesAvg\"), mean(\"inputBytesAvg\") FROM \"ftd_interfaceHealthMetrics\" WHERE (\"deviceName\"::tag =~ /^$deviceName$/ AND \"interface\"::tag =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval), \"interface\"::tag fill(null)",
     "select": [
      [
       { "params": [ "inputBytesAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" },
      { "condition": "AND", "key": "interface::tag", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "System Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_cpuHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_cpuHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"linaUsageAvg\" or r[\"_field\"] == \"snortUsageAvg\" or r[\"_field\"] == \"systemUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "systemUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "LINA Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_cpuHealthMetrics",
     "select": [
      [
       { "params": [ "linaUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "Snort Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_cpuHealthMetrics",
     "select": [
      [
       { "params": [ "snortUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU System Average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ftd_cpuHealthMetrics",
     "query": "  from(bucket: \"ftd\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_cpuHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"systemUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()\n",
     "select": [
      [
       { "params": [ "systemUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU LINA Average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_cpuHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_cpuHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"linaUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()\n",
     "select": [
      [
       { "params": [ "linaUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Snort Average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_cpuHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_cpuHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"snortUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "snortUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "System Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_memoryHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_memoryHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"linaUsageAvg\" or r[\"_field\"] == \"snortUsageAvg\" or r[\"_field\"] == \"systemUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "systemUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "LINA Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_memoryHealthMetrics",
     "select": [
      [
       { "params": [ "linaUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "Snort Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ftd_memoryHealthMetrics",
     "select": [
      [
       { "params": [ "snortUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory System Average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ftd_memoryHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_memoryHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"systemUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "systemUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory LINA Average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_memoryHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_memoryHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"linaUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "linaUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Snort Average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_memoryHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_memoryHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"snortUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "snortUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_diskHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_diskHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalDiskUsageAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "totalDiskUsageAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan 1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_chassisStatsHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_chassisStatsHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan1RpmAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "fan1RpmAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan 2",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_chassisStatsHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_chassisStatsHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan2RpmAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "fan2RpmAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan 3",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_chassisStatsHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_chassisStatsHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan3RpmAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "fan3RpmAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan 4",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ftd_chassisStatsHealthMetrics",
     "query": "from(bucket: \"ftd\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftd_chassisStatsHealthMetrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan4RpmAvg\")\n  |> filter(fn: (r) => r[\"deviceName\"] == \"${deviceName}\")\n  |> last()",
     "select": [
      [
       { "params": [ "fan4RpmAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "interface::tag" ], "type": "tag" }
     ],
     "measurement": "ftd_interfaceHealthMetrics",
     "query": "SELECT last(\"interfaceName\") AS \"Logical Name\",last(\"linkStatus\") AS \"Link Status\",last(\"bufferOverrunsAvg\") AS \"Overruns\", last(\"bufferUnderrunsAvg\") AS \"Underruns\", last(\"dropPacketsAvg\") AS \"Dropped Pkts Avg\",last(\"l2DecodeDropsAvg\") AS \"L2 Decode Drops Avg\",last(\"inputErrorsAvg\") AS \"Input Errors Avg\", last(\"outputErrorsAvg\") AS \"Output Errors Avg\",last(\"inputPacketSizeAvg\") AS \"Input Packet Size Avg\",last(\"outputPacketSizeAvg\") AS \"Output Packet Size Avg\" FROM \"ftd_interfaceHealthMetrics\" WHERE (\"deviceName\"::tag =~ /^$deviceName$/) AND $timeFilter GROUP BY \"interface\"::tag",
     "select": [
      [
       { "params": [ "bufferOverrunsAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Overruns" ], "type": "alias" }
      ],
      [
       { "params": [ "bufferUnderrunsAvg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Underruns" ], "type": "alias" }
      ],
      [
       { "params": [ "interfaceName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Logical Name" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "deviceName::tag", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  }
 ]
}